nodeLinker: pnp

packageExtensions:
  "@firebase/analytics-compat@*":
    peerDependencies:
      "@firebase/app": "*"
  "@firebase/auth-compat@*":
    peerDependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "@firebase/firestore-compat@*":
    peerDependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "@firebase/functions-compat@*":
    peerDependencies:
      "@firebase/app": "*"
  "@firebase/installations-compat@*":
    peerDependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
  "@firebase/messaging-compat@*":
    peerDependencies:
      "@firebase/app": "*"
  "@firebase/performance-compat@*":
    peerDependencies:
      "@firebase/app": "*"
  "@firebase/remote-config-compat@*":
    peerDependencies:
      "@firebase/app": "*"
  "@firebase/storage-compat@*":
    peerDependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"
